name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout commit
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Fetch history
        run: git fetch --prune --unshallow --recurse-submodules=no

      - name: Checkout Head Ref
        if: github.head_ref != ''
        run: |
          git checkout -b ${{ github.head_ref }} || git checkout ${{ github.head_ref }}

      - name: Install .NET 4.6.1 SDK
        shell: pwsh
        run: |
          $Arguments = (
            'modify', '--installPath', '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise"',
            '--quiet', '--norestart', '--nocache',
            '--add', 'Microsoft.Net.Component.4.6.1.SDK',
            '--add', 'Microsoft.Net.Component.4.6.1.TargetingPack'
          )
          $process = Start-Process -FilePath 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe' -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
          if ($process.ExitCode -ne 0) { exit 1 }

      - name: Set up msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Set up nuget
        uses: nuget/setup-nuget@v1

      - name: Set up vstest
        uses: darenm/setup-vstest@v1.2

      - name: Install NuGet packages
        run: nuget restore LiveSplit\LiveSplit.sln

      - name: Build LiveSplit
        run: msbuild LiveSplit\LiveSplit.sln /verbosity:minimal /p:NoWarn=1591 /p:Configuration=Release

      - name: Run tests
        run: |
          & "vstest.console.exe" "LiveSplit/LiveSplit.Tests/bin/Release/LiveSplit.Tests.dll"

      - name: Create a folder for the Server component artifacts
        run: |
          mkdir .\LiveSplit.Server
          Move-Item -path .\LiveSplit\bin\Release\Components\LiveSplit.Server.dll -destination .\LiveSplit.Server
          Move-Item -path .\LiveSplit\bin\Release\Components\Noesis.Javascript.dll -destination .\LiveSplit.Server

      - name: Upload the Server component as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: LiveSplit.Server
          path: LiveSplit.Server

      - name: Upload the Counter component as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: LiveSplit.Counter
          path: LiveSplit/bin/Release/Components/LiveSplit.Counter.dll

      - name: Clean up build folder
        run: |
          mkdir .\LiveSplit\bin\Release\Resources
          cp .\LiveSplit\Resources\SplitsFile.ico .\LiveSplit\bin\Release\Resources\
          cp .\LiveSplit\Resources\LayoutFile.ico .\LiveSplit\bin\Release\Resources\
          cd LiveSplit\bin\Release
          Get-ChildItem * -Include *.xml -Recurse | Remove-Item
          Get-ChildItem * -Include *.pdb -Recurse | Remove-Item
          Get-ChildItem * -Include *MSTest*.dll -Recurse | Remove-Item
          Get-ChildItem * -Include xunit.*.dll -Recurse | Remove-Item
          Get-ChildItem * -Include *LiveSplit.Counter.dll -Recurse | Remove-Item
          Get-ChildItem * -Include cef.pak,cef_100_percent.pak,cef_200_percent.pak,cef_extensions.pak,CefSharp.BrowserSubprocess.Core.dll,CefSharp.BrowserSubprocess.exe,CefSharp.Core.Runtime.dll,chrome_elf.dll,d3dcompiler_47.dll,devtools_resources.pak,icudtl.dat,libcef.dll,libEGL.dll,libGLESv2.dll,snapshot_blob.bin,v8_context_snapshot.bin | Remove-Item -Recurse
          Remove-Item locales -Recurse
          Remove-Item swiftshader -Recurse

      - name: Upload build as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: LiveSplit_Build
          path: LiveSplit/bin/Release

      - name: Upload build to LiveSplit.github.io
        if: github.repository == 'LiveSplit/LiveSplit' && github.ref == 'refs/heads/master'
        run: |
          7z a LiveSplitDevBuild.zip .\LiveSplit\bin\Release\*
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone -q --branch master --single-branch "https://github.com/LiveSplit/LiveSplit.github.io.git"
          cd LiveSplit.github.io
          git checkout -q --orphan artifacts
          git reset
          mv ../LiveSplitDevBuild.zip . -force
          git add LiveSplitDevBuild.zip
          git commit -m "Add Development Build"
          git push -q --force https://action:${{ secrets.DEV_BUILD_UPLOAD }}@github.com/LiveSplit/LiveSplit.github.io.git
